version: '2.29.1'
services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run po-chrome  # Moved command out of build
    volumes:
      - ./playwrite-report/:/app/playwrite-report
      - ./test-results/:/app/test-results
